services:
  employee:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL = jdbc:postgresql://postgres:5433/hotel
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres
    #image: postgres:16-alpine
    image: postgres:16
    #restart: always
    #user: postgres
    #user: "999:999"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'hotel'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 20s
      timeout: 20s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
volumes:
  pg_data: